version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: DockerfileBackend
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static_files
      - media_volume:/usr/src/app/media_files
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  redis:
    image: redis:7

  celery:
    build: 
      context: .
      dockerfile: DockerfileBackend
    restart: always
    command: celery -A config worker -l info
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_volume:/usr/src/app/static_files
      - media_volume:/usr/src/app/media_files
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: