# Generated by Django 4.1 on 2023-09-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_company_menuitem_menu_campany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
