# Generated by Django 4.1 on 2023-09-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('CRA', 'Criado'), ('SEN', 'Enviado'), ('OFD', 'Saiu para entrega'), ('DLD', 'Entregue')], max_length=20, null=True, verbose_name='Status do pedido'),
        ),
    ]
